name: Pre-Deployment Pipeline
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test ONNX Model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t my-image .
    - name: Convert PyTorch model to ONNX
      run: python convert_to_onnx.py
    - name: Run test cases on ONNX model
      run: python test_onnx_model.py
